Repository gihyo-book/ts-nextbook-app, pull requests merged in 2023-04, with the labels that each got.

#20 READMEへJSON Serverの設定と起動のことを追加
  README.md
Labels: documentation

#26 removeProductFromCart関数の不具合修正
  src/contexts/ShoppingCartContext/reducers.ts
Labels: bug

#22 出店→出品
  src/components/organisms/UserProfile/index.tsx
Labels: nits

#13 LINEをLETTERに変更
  src/utils/styles.ts
Labels: nits

#25 ユーザー名の表記ゆれ
  src/components/organisms/SigninForm/index.spec.tsx
  src/components/organisms/SigninForm/index.tsx
Labels: nits
